---
kind: pipeline
type: docker
name: apq8084

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-apq8084]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-apq8084 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh apq8084 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh apq8084 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: mdm9607

platform:
  os: linux
  arch: amd64

steps:
  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh mdm9607 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh mdm9607 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: msm8226

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8226]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8226 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8226 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8226 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: msm8610

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8610]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8610 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8610 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8610 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: msm8909

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8909]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8909 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8909 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8909 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

  - name: verified boot 1 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8909 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT=1]

  - name: verified boot 2 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8909 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT_2=1
               OSVERSION_IN_BOOTIMAGE=1 ENABLE_VB_ATTEST=1
               TARGET_USE_SYSTEM_AS_ROOT_IMAGE=1]

---
kind: pipeline
type: docker
name: msm8916

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8916]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8916 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8916 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8916 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: msm8952

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8952]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8952 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8952 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8952 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

  - name: verified boot 1 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8952 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT=1]

  - name: verified boot 2 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8952 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT_2=1
               OSVERSION_IN_BOOTIMAGE=1 ENABLE_VB_ATTEST=1 VB1_KEY_USED=1
               TARGET_USE_SYSTEM_AS_ROOT_IMAGE=1 ENABLE_KASLRSEED=1]

---
kind: pipeline
type: docker
name: msm8953

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8953]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8953 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8953 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8953 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

  - name: verified boot 1 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8953 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT=1]

  - name: verified boot 2 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8953 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT_2=1
               OSVERSION_IN_BOOTIMAGE=1 ENABLE_VB_ATTEST=1 VB1_KEY_USED=1
               TARGET_USE_SYSTEM_AS_ROOT_IMAGE=1 ENABLE_KASLRSEED=1]

  - name: dynamic partitions (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8953 LKLE_CFLAGS=-Werror
               DYNAMIC_PARTITION_SUPPORT=1 VIRTUAL_AB_OTA=1
               USER_BUILD_VARIANT=true VERIFIED_BOOT_2=1
               OSVERSION_IN_BOOTIMAGE=1 ENABLE_VB_ATTEST=1
               ENABLE_KASLRSEED=1]

---
kind: pipeline
type: docker
name: msm8960

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8960]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8960 LKLE_CFLAGS=-Werror]

---
kind: pipeline
type: docker
name: msm8974

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8974]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8974 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8974 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8974 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

---
kind: pipeline
type: docker
name: msm8994

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8994]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8994 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8994 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8994 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

  - name: verified boot 1 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8994 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT=1]

---
kind: pipeline
type: docker
name: msm8996

platform:
  os: linux
  arch: amd64

steps:
  - name: lk2nd (gcc10)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8996]

  - name: lk2nd (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh lk2nd-msm8996 LKLE_CFLAGS=-Werror]

  - name: default (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8996 LKLE_CFLAGS=-Werror]

  - name: signed kernel (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8996 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true SIGNED_KERNEL=1]

  - name: verified boot 1 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8996 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT=1]

  - name: verified boot 2 (gcc4)
    image: alpine:3.15
    commands: [./.drone.sh msm8996 LKLE_CFLAGS=-Werror
               USER_BUILD_VARIANT=true VERIFIED_BOOT_2=1
               OSVERSION_IN_BOOTIMAGE=1 ENABLE_VB_ATTEST=1 VB1_KEY_USED=1
               TARGET_USE_SYSTEM_AS_ROOT_IMAGE=1 ENABLE_KASLRSEED=1
               ENABLE_BOOTDEVICE_MOUNT=1]
